DROP TABLE if EXISTS users CASCADE;
DROP TABLE if EXISTS shows CASCADE;
DROP TABLE if EXISTS xref CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR(200),
  email VARCHAR(200),
  password_digest TEXT,
  bio VARCHAR(140)
);

CREATE TABLE shows (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR(200),
  seasons INTEGER DEFAULT 1,
  genre VARCHAR(20)
);

CREATE TABLE xref (
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  show_id INTEGER REFERENCES shows (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, show_id)
);
